export default {
  API_URL_Rest: 'https://api.binance.com/api/v3/',
  kindOfFlow: 'depth',
  limitRest: '20',
  lastUpdateId: '',
  tikersRest: '',
  API_WS: 'wss://stream.binance.com:9443/ws/stream',
  streamId: 1,
  tikersWS: '',
  itemsStream: [],
  itemsAsks: [],
  itemsBids: [],
  userAsks: [],
  userBids: [],
  connect: false,
  countAttempts: 0,
  socket: null,
  runStream: false,
  errorMessage: 0,
  haveResponseData: false,
};
